-- 従業員テーブル
CREATE TABLE IF NOT EXISTS employee (
    id INTEGER PRIMARY KEY ON CONFLICT FAIL AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    is_active INTEGER NOT NULL DEFAULT 1
);

-- 勘定科目マスタテーブル
CREATE TABLE IF NOT EXISTS m_title (
    id INTEGER PRIMARY KEY ON CONFLICT FAIL AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    is_active INTEGER NOT NULL DEFAULT 1
);

-- 勘定テーブル
CREATE TABLE IF NOT EXISTS account (
    id INTEGER PRIMARY KEY ON CONFLICT FAIL AUTOINCREMENT,
    date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    debit_title INTEGER NOT NULL REFERENCES m_title(id) ON DELETE CASCADE,
    credit_title INTEGER NOT NULL REFERENCES m_title(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    description TEXT NOT NULL,
    slip_id INTEGER REFERENCES slip(id) ON DELETE CASCADE
);

-- 振替伝票テーブル
CREATE TABLE IF NOT EXISTS slip (
    id INTEGER PRIMARY KEY ON CONFLICT FAIL AUTOINCREMENT,
    first_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    employee_in_charge INTEGER NOT NULL REFERENCES employee(id) ON DELETE CASCADE
);